x = input('digite algo:')
print('é do tipo', type(x))
print('é um alphanumérico: {}'.format(x.isalnum()))
print('é uma letra:', x.isalpha())
print('é um numero:', x.isnumeric())
print('é código ASCII:', x.isascii())
print('é um digito:', x.isdigit())
print('é um descimal:', x.isdecimal())
print('é valido para um identificador de código:', x.isidentifier())
print('estão em minúsculas:', x.islower())
print('estão em maiúsculas:', x.isupper())
print('pode ser impresso (na tela ou folha):', x.isprintable())
print('é um espaço', x.isspace())
print('a primeira letra é maiuscula', x.istitle())

